[colors.bright]
black = "0x686868"
blue = "0x59C2FF"
cyan = "0x95E6CB"
green = "0xC2D94C"
magenta = "0xFFEE99"
red = "0xF07178"
white = "0xFFFFFF"
yellow = "0xFFB454"

[colors.cursor]
cursor = "0x0abdc6"
text = "0x000b1e"

[colors.dim]
black = "0x31363b"
blue = "0x1b668f"
cyan = "0x186c60"
green = "0x17a262"
magenta = "0x614a73"
red = "0x783228"
white = "0x63686d"
yellow = "0xb65619"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x01060E"
blue = "0x53BDFA"
cyan = "0x90E1C6"
green = "0x91B362"
magenta = "0xFAE994"
red = "0xEA6C73"
white = "0xC7C7C7"
yellow = "0xF9AF4F"

[colors.primary]
background = "0x0A0E14"
foreground = "0xB3B1AD"

[colors.search.focused_match]
background = "CellForeground"
foreground = "CellBackground"

[colors.search.matches]
background = "0xb26818"
foreground = "0xb2b2b2"

[colors.selection]
background = "0xb3d7ff"
text = "0x000000"

[colors.vi_mode_cursor]
cursor = "0x524f67"
text = "0xe0def4"

[font]
size = 13

[schemes.ayu_dark.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[schemes.ayu_dark.normal]
black = "#1f1f1f"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[schemes.ayu_dark.primary]
background = "#000000"
foreground = "#B3B1AD"

[schemes.solarized_light.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized_light.cursor]
cursor = "#657b83"
text = "#fdf6e3"

[schemes.solarized_light.normal]
black = "#1f1f1f"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized_light.primary]
background = "#fdf6e3"
foreground = "#657b83"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = 'Both'

[terminal]
