[keys.normal]
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
"C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
