[[language]]
name = "python"

[language.config.pylsp.plugins]
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}

[language.config.pylsp.plugins.flake8]
enabled = true
maxLineLength = 120

[language.config.completion.snippets.custom.ipdb]
prefix = ["ipdb"]
body = ["__import__('ipdb').set_trace()"]
description = "Insert IpDB call."
scope = "expr"
