# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  ethernets:
    name_of_ethernet_device(eg enp0s25):
      dhcp4: false
      addresses: [192.168.y.zzz/24] # y is home network, zzz is desired ip
      gateway4: 192.168.y.1
      nameservers:
        addresses: [8.8.8.8,1.1.1.1]
