- hosts: new-machine
  become: yes
  become_user: root
  vars:
    local_user: ffettes
    default_users:
      - ffettes
      # - mfettes
      # - work
    user_groups: docker,sudo
    passwords_folder: "/home/ffettes/.password-store/"
    maximal: yes
    local_install: yes
    cuda: yes
    gpu: yes
  tasks:

    - name: Update and upgrade all apt packages
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Install NVIDIA
      include_role:
        name: nvidia.nvidia_driver
      when: cuda
    - name: Install CUDA stuff
      include_role:
        name: tyhal.cuda
      when: cuda

    - name: ruby gems
      include_role:
        name: geerlingguy.ruby
      vars:
        ruby_install_gems: [tmuxinator]
      when: maximal

    # This is here because docker needs to be installed for the next section to work properly
    - name: include pip role
      include_role:
        name: geerlingguy.pip
      vars:
        pip_executable: pip3
        pip_install_packages:
          - td-cli
          - togglCli
          - cookiecutter
          - virtualenv
          - docker
          - docker-compose
          - numpy
          - pandas
          - matplotlib
          - pytest
          - ipython
          - ipdb
          - pre-commit
          - neovim
          # for ALE
          - flake8
          - pylint
          - mypy
          - bump2version
          - poetry
          - se
      when: maximal
    - name: include docker role
      include_role:
        name: geerlingguy.docker

    - name: Create default users
      user:
        name: "{{ item }}"
        groups: "{{ user_groups }}"
        shell: /bin/bash
        password: "{{ lookup('password', passwords_folder + 'masked-' + item|string + ' length=64 chars=ascii_letters,digits')}}"
      with_items:
        - "{{ default_users }}"
      when: maximal
    - name: Add user to sudo
      lineinfile:
        path: "/etc/sudoers.d/{{ item }}"
        line: "{{ item }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: yes
        validate: 'visudo -cf %s'
      with_items:
        - "{{ default_users }}"
      when: maximal
    - name: copy ssh keys for user
      synchronize:
        src: "~/.ssh/"
        dest: "/home/ffettes/.ssh"
      when: maximal

    - name: Add specified repository into sources list using specified filename.
      apt_repository:
        repo: "{{ item }}"
      with_items:
        # - 'ppa:regolith-linux/release'
        - 'ppa:neovim-ppa/unstable'

    - name: install standard ubuntu packages
      apt:
        update_cache: yes
        pkg:
          # improved ssh tunelling/net tools
          - mosh
          - unzip
          - curl
          - nfs-common
          - net-tools
          - openssh-server
          - fping
          - xclip
          # command line tools for navigation etc
          - tree
          - ranger
          - parallel
          - zsh
          - tmux
          - fzf
          - silversearcher-ag
          - jq
          - stow
          - ripgrep
          - vim
          - python3-neovim
          - ncdu
          - fdupes
          # development tools
          - git
          - git-flow
          - python3-pip
          - python3-dev
          - htop
          - cmake
          - software-properties-common
          - virtualenv
          - ansible
          - pwgen
          - apache2-utils
          - zoxide
          - libxkbcommon-dev
          - sqlite3
          - pandoc
          - poppler-utils
          - shotwell
          - shellcheck
          # Pdf stuff
          - libpoppler-cpp-dev
          - pkg-config
          - tesseract-ocr
          - ffmpeg
          - ocrmypdf
          - bat
          - arbtt
          - xdotool

    - name: install extra ubuntu packages
      apt:
        update_cache: yes
        pkg:
          # ubuntu tools
          - indicator-multiload
          - gnome-tweaks
          - pavucontrol
          - tlp
          - linux-tools-common
          - linux-tools-generic
          # Regolith
          # - regolith-desktop-standard
          # - i3xrocks-net-traffic
          # - i3xrocks-cpu-usage
          # - i3xrocks-time
          # deps for alacritty
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          # other tools
          - pandoc
          - inkscape
          - hugo
          - lynx
          - feh
          - vlc
          - mpv
          # - nvidia-cuda-toolkit
      when: maximal
    - name: uninstall ubuntu stuff
      apt:
        pkg:
          - gnome-shell-extension-desktop-icons
          - gnome-shell-extension-ubuntu-dock
        state: absent
      when: maximal

    - name: include pip role
      include_role:
        name: geerlingguy.pip
      vars:
        pip_executable: pip3
        pip_install_packages:
          - pdftotext

    - name: install cargo for alacritty and dust
      block:
        - name: install cargo
          include_role:
            name: robertdebock.cargo
        - name: Rust clones
          git:
            repo: "https://github.com/{{ item }}"
            dest: "/home/ffettes/.cargo/"
            accept_hostkey: yes
            depth: 1
            recursive: yes
            version: master
          with_items:
            - "alacritty/alacritty.git"
          become: no
        - name: Rust builds
          shell:
            cmd: "cargo build --release"
            chdir: "/home/ffettes/.cargo/{{ item }}"
          with_items:
            - "alacritty"
        - name: Install alacritty build
          file:
            src: "/home/ffettes/.cargo/target/release/alacritty"
            path: "/usr/bin/alacritty"
            state: link
        # - name: Other Cargo installs
        #   shell:
        #     cmd: "cargo install du-dust"
        #   sudo: true
      when: maximal

    - name: install fd
      include_role:
        name: "gantsign.{{ item }}"
      with_items:
        - fd
        - ctop
        # - swapspace
        # - zswap

    - name: install oh-my-zsh and completion
      include_role:
        name: gantsign.antigen
      vars:
        users:
          - username: ffettes
            antigen_libraries:
              - name: oh-my-zsh
            antigen_bundles:
              - name: hub
              - name: git
              - name: git-flow
              - name: pip
              - name: command-not-found
              - name: sudo
              - name: python
              - name: poetry
              - name: k
                url: supercrabtree/k
              - name: zsh-syntax-highlighting
                url: zsh-users/zsh-syntax-highlighting
              - name: zsh-autosuggestions
                url: zsh-users/zsh-autosuggestions
              - name: zsh-navigation-tools
                url: psprint/zsh-navigation-tools
              - name: zsh-cmd-architect
                url: psprint/zsh-cmd-architect
        antigen_install_oh_my_zsh: yes
    - name: place oh-my-zsh where you expect it
      file:
        src: "/home/ffettes/.antigen/bundles/robbyrussell/oh-my-zsh"
        path: "/home/ffettes/.oh-my-zsh"
        state: link
      become: no
    - name: Install enhancd
      git:
        repo: "https://github.com/b4b4r07/enhancd"
        dest: "/home/ffettes/custom/plugins/"
        accept_hostkey: yes
        depth: 1
        recursive: yes
        version: master
      become: no

    - name: Download diskus
      get_url:
        url="https://github.com/sharkdp/diskus/releases/download/v0.7.0/diskus_0.7.0_amd64.deb"
        dest="/home/ffettes/Downloads/diskus.deb"
    - name: Download pastel
      get_url:
        url="https://github.com/sharkdp/pastel/releases/download/v0.8.1/pastel_0.8.1_amd64.deb"
        dest="/home/ffettes/Downloads/pastel.deb"

    - name: Install debs
      apt: deb="/home/ffettes/Downloads/{{ item }}"
      with_items:
        - "diskus.deb"
        - "pastel.deb"

    - name: Download etcher
      get_url:
        url="https://github.com/balena-io/etcher/releases/download/v1.7.9/balena-etcher-electron-1.7.9-linux-x64.zip"
        dest="/home/ffettes/.local/etcher"
    - name: Install etcher
      file:
        src: "/home/ffettes/.local/etcher"
        path: "/usr/bin/etcher"
        state: link

    - name: Create dirs for vim plug
      file:
        path: "/home/ffettes/.local/share/nvim/site/autoload/"
        state: directory
        group: ffettes
        owner: ffettes
    - name: Download vim plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "/home/ffettes/.local/share/nvim/site/autoload/plug.vim"
    - name: Clone dotfiles
      git:
        repo: "https://github.com/fergusfettes/dotfiles"
        dest: "/home/ffettes/dotfiles"
        accept_hostkey: yes
        depth: 1
        recursive: yes
        version: master
      become: no
      when: local_install
    - name: Clear out .zshrc
      file:
        path: "/home/ffettes/.zshrc"
        state: absent
    - name: Stow dotfiles
      shell:
        cmd: "stow {{ item }}"
        chdir: "/home/ffettes/dotfiles/"
      with_items:
        - "alacritty"
        - "ansible"
        - "git"
        - "ipython"
        - "ranger"
        - "regolith"
        # - "pip"
        # - "ssh"
        - "pylintrc"
        - "tmuxinator"
        - "tmux"
        - "vim"
        # - "zsh"
        - "arbtt"
      become: no

    - name: Clone Tmux package manager
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "/home/ffettes/.tmux/plugins/tpm"
        depth: 1
        recursive: no
      become: no
    - name: Clone bat-extras
      git:
        repo: "https://github.com/eth-p/bat-extras"
        dest: "/home/ffettes/.local/bat-extras"
        depth: 1
        recursive: no
      become: no
